# Generated by Django 3.1.4 on 2021-01-06 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RujukanKarantina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daerah', models.CharField(default='', max_length=255)),
                ('namaRS', models.CharField(default='', max_length=255)),
                ('namaTempatKarantina', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
