# Generated by Django 3.1.4 on 2021-01-06 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karantina', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rujukankarantina',
            old_name='daerah',
            new_name='Kabupaten',
        ),
        migrations.AddField(
            model_name='rujukankarantina',
            name='kecamatan',
            field=models.CharField(default='', max_length=255),
        ),
    ]
