# Generated by Django 3.1.4 on 2021-01-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPasien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daerah', models.CharField(default='', max_length=100)),
                ('P_Positif', models.DecimalField(decimal_places=0, max_digits=6)),
                ('P_Meninggal', models.DecimalField(decimal_places=0, max_digits=6)),
                ('P_Sembuh', models.DecimalField(decimal_places=0, max_digits=6)),
            ],
        ),
    ]
