# Generated by Django 3.1.4 on 2020-12-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataCovid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('pasien_positif', models.DecimalField(decimal_places=10, max_digits=10)),
                ('pasien_kontakerat', models.DecimalField(decimal_places=10, max_digits=10)),
                ('pasien_sembuh', models.DecimalField(decimal_places=10, max_digits=10)),
            ],
        ),
    ]
