# Generated by Django 3.1.4 on 2020-12-29 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datacovid',
            name='data',
        ),
        migrations.RemoveField(
            model_name='datacovid',
            name='pasien_kontakerat',
        ),
        migrations.RemoveField(
            model_name='datacovid',
            name='pasien_positif',
        ),
        migrations.RemoveField(
            model_name='datacovid',
            name='pasien_sembuh',
        ),
    ]
