# Generated by Django 3.1.4 on 2020-12-30 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20201229_1654'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataCovid',
            new_name='pasien',
        ),
    ]
