# Generated by Django 3.1.4 on 2020-12-30 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20201230_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasien',
            name='judul',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='pasien',
            name='pasien_kontakerat',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='pasien',
            name='pasien_positif',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='pasien',
            name='pasien_sembuh',
            field=models.TextField(default=''),
        ),
    ]
