# Generated by Django 3.1.4 on 2021-01-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_auto_20201230_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='fotojudul',
            field=models.FileField(default='', upload_to='static/imgFile/'),
        ),
    ]
