# Generated by Django 3.1.4 on 2021-01-02 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_auto_20210102_0903'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadDocument',
        ),
    ]
