# Generated by Django 3.1.4 on 2021-01-03 03:40

from django.db import migrations, models
import info.models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0014_auto_20210102_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='FotoJudul',
            field=models.ImageField(upload_to=info.models.path_and_rename),
        ),
    ]
