# Generated by Django 3.1.4 on 2021-01-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harga',
            name='hargaRapid',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='harga',
            name='hargaSwab',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
    ]
